# User config
author: "Terry"
tagline: "Terry PortFolio"
description: ""
keywords: "Terry, portfolio"
email: "soomis7@icloud.com"
github: "https://github.com/jeonsumin"
blog: "https://blog.naver.com/soomis7"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed